import React, {useEffect, useState} from "react";
import {api} from "./api";
import {copyDefaults} from "./site-copy";
import Icon from "./icons";
const labels = {informationTitle:"Information heading",informationBody:"About the project",informationGuide:"How to use the map",organiser:"Menu organiser line",informationCredit:"Developer credit introduction",campaignLabel:"Campaign page button",offersTitle:"Offers sidebar heading",informationLabel:"Information menu label",informationSubtitle:"Information menu description",submissionTitle:"Submission heading and menu label",submissionSubtitle:"Submission menu description",submissionIntro:"Submission introduction",cookieText:"Cookie message"};
export default function AdminSettings({user}) {
 const [values,setValues]=useState(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{api("settings").then(s=>setValues({...s,analyticsInput:(s.gaIds||[]).join("\n")})).catch(e=>setError(e.message));},[]);
 async function save(e){e.preventDefault();setBusy(true);setError("");setMessage("");try{const {analyticsInput,...body}=values;const saved=await api("settings",{...body,...(user.role==="super-admin"?{analyticsInput}:{})});setValues({...saved,analyticsInput:(saved.gaIds||[]).join("\n")});setMessage("Settings saved. The website will pick up the changes on refresh.");}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="site-settings"><h1>Website settings</h1><p>Edit the public menu, information and submission copy. Leave a text field blank to use its default wording.</p>{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="success" role="status">{message}</p>}{values&&<form onSubmit={save}><div className="settings-grid">{Object.entries(labels).map(([key,label])=><label key={key}>{label}<textarea rows={key.includes("Body")||key.includes("Guide")?5:3} maxLength={key==='informationBody'?5000:key==='informationGuide'?3000:key==='cookieText'||key==='submissionIntro'?1000:key==='informationCredit'?500:key==='organiser'?300:key.includes('Subtitle')?200:120} placeholder={copyDefaults[key]} value={values[key]||""} onChange={e=>setValues({...values,[key]:e.target.value})}/></label>)}</div>{user.role==="super-admin"?<fieldset><legend>Google Analytics</legend><p>Paste GA4 measurement IDs (G-...) or Google Analytics installation snippets. Only the IDs are saved; standard Google tags are installed in the page head after visitors allow analytics. Arbitrary scripts and Google Tag Manager containers are not supported. Analytics is disabled in local demo mode.</p><label>Measurement IDs or Google snippets<textarea rows={6} maxLength={20000} value={values.analyticsInput} onChange={e=>setValues({...values,analyticsInput:e.target.value})}/></label><small>Leave empty to disable analytics. Up to five measurement IDs.</small></fieldset>:<p>Analytics configuration is managed by a super-admin.</p>}<button className="button primary" disabled={busy}><Icon name="check"/>{busy?"Saving…":"Save settings"}</button></form>}</section>;
}
